home-work featers 01
novopashinwm/IntensivStar pull request #1
Opened 2020-10-06 19:04 UTC by novopashinwm

HW 01

2020-10-06 21:14 UTC, AndroidStudentClub requested changes
В целом, пока неплохо, классно что раньше всех сделали.Но! Стоит внимание уделить вёрстке экрана который отображает сериалы - так как она не по макету (Возможно в процессе и просто пока не успели).
Переходы на фильмы сломаны - так как используется собственная invoke - видимо для дебага (вообще оно лишнее).
Нужно избегать дублирования кода. Стоит уделить внимание форматированию кода - это хоть и кажется не очень важным, но на code review тестовых заданий на это сразу же обращают внимание.
Кроме того есть баг с рейтингом

2020-10-06 21:14 UTC, AndroidStudentClub commented on app/src/main/res/layout/tv_shows_fragment.xml
> +        <LinearLayout
А зачем LinearLayout? RecyclerView может сам отобразить весь список ячеек. Ему не нужны никакие контейнеры. LinearLayout мог бы пригодиться если у нас есть несколько элементов (кнопки/тексты) которые надо как то скомпоновать

2020-10-06 21:14 UTC, AndroidStudentClub commented on app/src/main/res/layout/tv_shows_fragment.xml
> +            <androidx.recyclerview.widget.RecyclerView
По макету список сериалов вертикальный, однако в данный момент у нас все ячейки горизонтально скролятся. Это все потому что мы используем общий контейнер MainCardContainer. Выше писал что надо создать ячейку по макету и добавлять в адаптер эти ячейки - тогда они отобразятся вертикально.

2020-10-06 21:14 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/tvshows/TvShowsFragment.kt
> +                }?.toList()?.let { MainCardContainer(R.string.tv_shows, it) })
MainCardContainer здесь лишний - так как он нужен был только для вложенных ячеек. Здесь же ячейки сериалов будут просто скролиться вниз

2020-10-06 21:14 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL ="https://api.themoviedb.org/3/"
В целом, хорошей практикой является вынесение базового урл в build.gradle как мы выносили API_KEY.         `buildConfigField 'String', 'THE_MOVIE_DATABASE_API', keystoreProperties['THE_MOVIE_DATABASE_API']`

Это может пригодится, когда у нас разные урл (например один для тестового билда/второй для настоящего который в проде)

Вот статья на эту тему https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6
Смотреть пункт #3 Way: Using Gradle Build Config Fields

2020-10-06 21:16 UTC, AndroidStudentClub commented
> HW 01

Для Pull requests в целом стоит кратко описать проделанную работу: например 

Добавлено отображение списка фильмов на главной и на экране сериалов
Страница деталей будет в следующем пр

В реальной работе обычно так всегда делают

2020-10-07 14:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +    var getPopular = MovieApiClient.apiClient.getPopular(API_KEY,"ru")
А ещё можно вынести язык в строковый ресурс для соответствующей локали ru. То есть если пользователь скачает приложение в Англии или Германии, то было бы логично запрашивать фильмы на английском или немецком языке. Так вот, андроид автоматически определит локаль пользователя и попытается найти строки из папки values-en/ или values-de/ И если там будет строка с нужным параметром (например для английского en) - то если в запросе мы будем использовать строку из ресурсов то автоматом подтянется нужный параметр. Подробнее можно почитать https://habr.com/ru/post/133503/ Раздел Локализация строк

2020-10-08 14:42 UTC, novopashinwm commented on app/src/main/res/layout/tv_shows_fragment.xml
> +            <androidx.recyclerview.widget.RecyclerView
Как это сделать?

2020-10-08 14:52 UTC, AndroidStudentClub commented on app/src/main/res/layout/tv_shows_fragment.xml
> +            <androidx.recyclerview.widget.RecyclerView
Вы уже создали TVItem. Теперь нужно

- [ ] Создать xml-верстку одной ячейки (Картинка+текст+рейтинг)

- [ ] В Методе getlayout() в TVItem вернуть layout верстки

- [ ] Использовать TvItem как ниже но без MainCardContainer

2020-10-09 08:14 UTC, AndroidStudentClub approved these changes
Дз, принято, смёржу в master. Только не забудьте поправить логику деления на 2- лучше её вынести в метод модели movie. Ветку для следующего ДЗ от мастера точно так же делайте

2020-10-09 08:14 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/MovieItem.kt
> +        viewHolder.movie_rating.rating = (content.voteAverage.toFloat()/2.0).toFloat()
Да, разделить на 2 - нормальное решение. Вот только нужно чтобы логика была частью модели. Нужно это реализовать в методе или свойстве модели Movie. Так будет лучше потому что если нам нужно еще в других местах использовать такую же логику - то не придётся копировать одно и тоже. К тому же, если поменяется алгоритм нормализации оценки (например у нас теперь максимум 3 звезды и надо делить на 3 например) - то везде придётся это менять. А так только в одном месте. В общем принцип DRY - никто не отменял)

2020-10-09 08:14 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/tvshows/TVItem.kt
> +        viewHolder.movie_rating.rating = (content.voteAverage.toFloat()/2.0).toFloat()
Об этом говорил выше

2020-10-09 10:25 UTC, merged