home work 04
novopashinwm/IntensivStar pull request #3
Opened 2020-10-18 19:48 UTC by novopashinwm

1) Add DTO objects.
2) Enable MovieDetailsFragment

2020-10-19 14:13 UTC, AndroidStudentClub requested changes
Не доделано :( Созвонимся и пройдемся по коментариям на консультации

2020-10-19 14:13 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/dto/MovieDatabase.kt
> +@Database(entities = [MovieDto::class], version = 1)
Не, БД не в dto надо а можно отдельную папку создать.
Dto - это Data Transfering Objects
Data Transfer Object (DTO) — один из шаблонов проектирования, используется для передачи данных между подсистемами приложения. Data Transfer Object, в отличие от business object или data access object не должен содержать какого-либо поведения.

2020-10-19 14:13 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/network/MovieDetailsResponse.kt
> +data class MovieDetailsResponse(
Раз уж начали в DTO перемещать то это тоже в dto

2020-10-19 14:13 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/network/MovieDetailsResponse.kt
> +    data class Genre(
И это

2020-10-19 14:13 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/network/MovieDetailsResponse.kt
> +    data class ProductionCompany(
И это.
Кстати не обзательно делать их частью класса MovieResponse
Можно отдельным классом

2020-10-19 14:13 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/dto/MovieDatabase.kt
> +@Database(entities = [MovieDto::class], version = 1)
У вас сейчас entity смешано.
C одной стороны это MovieDto для работы с сетью
С другjq - этот же класс используется и для хранения данных
Рекомендуется их разделять. Создайте MovieEntity - и используйте чисто его для создания таблицы
При этом когда вы получаете DTO от ретрофита вам нужен класс маппер -который будет конвертировать MovieDto в MovieEntity

2020-10-23 15:24 UTC, AndroidStudentClub requested changes

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                    val db = context?.let { it1 -> MovieDatabase.get(it1).movieDao() }
Да тут можно и не проверять контекст - можно заменить всё это вот так
MovieDatabase.get(requereContext()).movieDao()

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                    if (db != null) {
Проверки на null лучше через let делать - это более kotlin way

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/MainActivity.kt
> +            .subscribeOn(Schedulers.io())
Уже же есть init - экстеншн - его можно использовать чтобы не повторять

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                        db.insert(movie)
Не, это выглядит топорно - можно использовать update
 @Update
    fun update(movieDB: MovieDB): Completable

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +                        db.insert(movie)
update можно использовать

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +                        val movie:MovieDB = convertMovie(mv)
В целом конечно так тоже можно, но это не очень.
1) Конвертирование данных из 1-го типа в другой может занимать время. Для 10 элеменетов это не будет влиять - но если из много и много запросов - то лучше практика обычно выносить это в оператор map в RxJava цепочку
2) В Subsrcribe вы работает а базой - тк выше был init() в котором было переключение на MainThread -  то получается тут вы работаете с базой в главном потоке - тогда будет краш (если эта опция отключена у БД)

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +                        val movie:MovieDB = convertMovie(mv)
Поэтому лучше тут использовать оператор rxJava map, а для сохранения данных можно потом flatMap

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +                        val movie:MovieDB = convertMovie(mv)
Приме того как это может выглядеть:
  ```
 .map {
                MovieMapper.toValueObject(it)
            }
            .map {
                val movies = MovieVoToNowPlayingMovieMapper.toNowPlayingMovieEntity(it)
                database.nowPlayingMovieDao().insertAll(movies)
                return@map it
            }
```

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/ui/feed/FeedFragment.kt
> +                .subscribeOn(Schedulers.io())
init()

2020-10-23 15:24 UTC, AndroidStudentClub commented on app/src/main/res/layout/heart_btn.xml
> +    android:layout_height="39dp"
Это лучше выносить в ресурсы

2020-10-26 07:07 UTC, novopashinwm commented on app/src/main/res/layout/heart_btn.xml
> +    android:layout_height="39dp"
Не совсем понял как это сделать

2020-10-26 21:15 UTC, AndroidStudentClub commented on app/src/main/res/layout/heart_btn.xml
> +    android:layout_height="39dp"
В папке values есть xml-файл dimens.xml
В нём можно описывать разные значения которые относятся к размерам
Создаём там

    <dimen name="checkbox_size">39dp</dimen>
Потом используем его в верстке   android:layout_height="@dimens/checkbox_size"

2020-10-27 20:23 UTC, AndroidStudentClub requested changes

2020-11-03 10:29 UTC, AndroidStudentClub approved these changes
Проверил, написал парочку новых и увидел что старые не все поправлены

2020-11-03 10:29 UTC, AndroidStudentClub commented on app/build.gradle
> +    implementation 'androidx.room:room-rxjava2:2.2.2'
Не вынесены в константы

2020-11-03 10:29 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/MainActivity.kt
> +
В реальных проектах пустые строчки/неформатированный код - лучше не использовать. Тут даже дело не в "красоте". Когда проект разрабатывает несколько человек - то часто меняются одни и теже файлы - получаются мёрдж конфликты. Вот как раз чем меньше строк меняется - тем меньше мердж конфликтов

2020-11-03 10:29 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/db/MovieDao.kt
> +    //А Room переварит List<MovieEntity>?
Да, Room умеет сохранять List<T> в качестве аргумента. Не сможет если сложный тип используется в качестве столбца

2020-11-03 10:29 UTC, AndroidStudentClub commented on app/src/main/java/ru/mikhailskiy/intensiv/db/MovieDao.kt
> +    @Transaction
Да не Transaction тут не нужен, это нужно когда у вас сложные запросы где отношения 1 ко многим или многие - ко многим, потому что там часто рум делает выборку из 2 запросов а тут просто получить фильмы по id

2020-11-10 18:24 UTC, AndroidStudentClub approved these changes
Можно смёржить

2020-11-10 18:41 UTC, merged